1

   Abaqus 2025                                  Date 28-5ÔÂ-2026   Time 00:59:24
   For use by Supplied by Team-SolidSQUAD under license from Dassault Systemes or its subsidiary.

 Wide electrode calendering 1/8 equivalent static model                          
                                                                                 
 STEP    1     INCREMENT     1     STEP TIME    0.00    


                        A N A L Y S I S    D A T A C H E C K




                        S T E P       1     S T A T I C   A N A L Y S I S


                                                                                          

     AUTOMATIC TIME CONTROL WITH -
          A SUGGESTED INITIAL TIME INCREMENT OF                2.000E-02
          AND A TOTAL TIME PERIOD OF                            1.00    
          THE MINIMUM TIME INCREMENT ALLOWED IS                1.000E-08
          THE MAXIMUM TIME INCREMENT ALLOWED IS                5.000E-02

     LINEAR EQUATION SOLVER TYPE         DIRECT SPARSE

     ADAPTIVE AUTOMATIC STABILIZATION WITH 
     INITIAL DISSIPATED ENERGY FRACTION  =   2.000E-04

     COLLECTING MODEL CONSTRAINT INFORMATION FOR OVERCONSTRAINT CHECKS

     COLLECTING STEP CONSTRAINT INFORMATION FOR OVERCONSTRAINT CHECKS



     JOB TIME SUMMARY
       USER TIME (SEC)      =      32.    
       SYSTEM TIME (SEC)    =      1.6    
       TOTAL CPU TIME (SEC) =      34.    
       WALLCLOCK TIME (SEC) =           35
       MEMORY PEAK (GB)     =            0
