1

   Abaqus 2025                                  Date 23-Jun-2026   Time 04:30:43
   For use by Supplied by Team-SolidSQUAD under license from Dassault Systemes or its subsidiary.

 Local static symmetric normal press model with rigid rollers                    
                                                                                 
 STEP    1     INCREMENT     1     STEP TIME    0.00    


                        A N A L Y S I S    D A T A C H E C K




                        S T E P       1     S T A T I C   A N A L Y S I S


                                                                                          

     AUTOMATIC TIME CONTROL WITH -
          A SUGGESTED INITIAL TIME INCREMENT OF                1.000E-03
          AND A TOTAL TIME PERIOD OF                            1.00    
          THE MINIMUM TIME INCREMENT ALLOWED IS                1.000E-12
          THE MAXIMUM TIME INCREMENT ALLOWED IS                5.000E-03

     LINEAR EQUATION SOLVER TYPE         DIRECT SPARSE

     AUTOMATIC STABILIZATION WITH DISSIPATED ENERGY FRACTION =  2.000E-04

     COLLECTING MODEL CONSTRAINT INFORMATION FOR OVERCONSTRAINT CHECKS

     COLLECTING STEP CONSTRAINT INFORMATION FOR OVERCONSTRAINT CHECKS



     JOB TIME SUMMARY
       USER TIME (SEC)      =      1.4    
       SYSTEM TIME (SEC)    =      0.0    
       TOTAL CPU TIME (SEC) =      1.4    
       WALLCLOCK TIME (SEC) =            1
       MEMORY PEAK (GB)     =            0
